### ISSUE TITLE
Alive Transport

### ISSUE THREAD

**Issue by WarlordX07** [71stSOG/MissionTemplate#9]
Would like to add Alive mod with the Transport Choppers, Reason is to remove teleporting from game.

**Comment by dixon13** [comment]
if ALiVE mod is being added then we probably don't need the view distance script correct?

**Comment by WarlordX07** [comment]
the alive view distance sucks and i prefer this one more

**Comment by dixon13** [comment]
Ok this will stay in then

**Comment by dixon13** [comment]
Just want to reference that if anyone else besides myself or Hef is looking at this, we are referring to my fork, which can be found here: https://github.com/dixon13/MissionTemplate

**Comment by WarlordX07** [comment]
added 2x BlackHawk, 2x LittleBirds, 1x CH47, 1x Gunship
